/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.letscodegradle;


import java.util.Arrays;

public class App {

    public static void main(String[] args) {


        //vetores
        Pessoa pessoa1 = new Pessoa();
        pessoa1.setNome("Joao");
        pessoa1.setIdade(16);

        Pessoa pessoa2 = new Pessoa();
        pessoa2.setNome("Jose");
        pessoa2.setIdade(20);

        Pessoa pessoa3 = new Pessoa();
        pessoa3.setNome("Maria");
        pessoa3.setIdade(34);

        Pessoa pessoa4 = new Pessoa();
        pessoa4.setNome("Alfredo");
        pessoa4.setIdade(56);

        ListaDePessoas listaDePessoas = new ListaDePessoas();
        listaDePessoas.adicionar(pessoa1);
        listaDePessoas.adicionar(pessoa2);
        listaDePessoas.adicionar(pessoa3);
        listaDePessoas.adicionar(pessoa4);

        System.out.println("\nListando todos: ");
        listaDePessoas.listarTodos();
//        System.out.println(Arrays.toString(pessoas));

        System.out.println("\nBuscando por nome: ");
        Pessoa teste =  listaDePessoas.buscar("Joao");
        System.out.println(teste);

        Pessoa teste2 =  listaDePessoas.buscar("nada");
        System.out.println(teste2);

        System.out.println("\nBuscando por indice: ");
        Pessoa teste3 = listaDePessoas.getPessoa(2);
        System.out.println(teste3);

        Pessoa teste4 = listaDePessoas.getPessoa(10);
        System.out.println(teste4);

        System.out.println("\nRemovendo pessoa: ");
        listaDePessoas.remover(pessoa2);
        listaDePessoas.listarTodos();

    }
}
